name: convert-to-sarif

on: workflow_dispatch

jobs:
  upload-sarif:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: airtower-luna/convert-to-sarif@main
        with:
          tool: 'Sonar'
          input_file: 'report.xml'
          sarif_file: 'report.sarif'
      
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif
          category: cppcheck
